services:
  serverManchester:
    image: debian
    container_name: serverManchester
    networks:
      custom-net:
        ipv4_address: 192.168.1.30
    ports:
      - "127.168.1.30:22:22"
    volumes:
      - C:\Users\juang\.ssh\id_rsa.pub:/root/.ssh/authorized_keys
    command: /bin/bash -c "\
      apt update && \
      apt install -y openssh-server && \
      mkdir -p /root/.ssh && \
      chown root:root /root/.ssh/authorized_keys && \
      chmod 600 /root/.ssh/authorized_keys && \
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      mkdir -p /run/sshd && \
      /usr/sbin/sshd -D"
    
  serverMadrid:
    image: debian
    container_name: serverMadrid
    networks:
      custom-net:
        ipv4_address: 192.168.1.20
    ports:
      - "127.168.1.20:23:22"
    volumes:
      - C:\Users\juang\.ssh\id_rsa.pub:/root/.ssh/authorized_keys
    command: /bin/bash -c "\
      apt update && \
      apt install -y openssh-server && \
      mkdir -p /root/.ssh && \
      chown root:root /root/.ssh/authorized_keys && \
      chmod 600 /root/.ssh/authorized_keys && \
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      mkdir -p /run/sshd && \
      /usr/sbin/sshd -D"

  serverOslo:
    image: debian
    container_name: serverOslo
    networks:
      custom-net:
        ipv4_address: 192.168.1.10
    ports:
      - "127.168.1.10:24:22"
    volumes:
      - C:\Users\juang\.ssh\id_rsa.pub:/root/.ssh/authorized_keys
    command: /bin/bash -c "\
      apt update && \
      apt install -y openssh-server && \
      mkdir -p /root/.ssh && \
      chown root:root /root/.ssh/authorized_keys && \
      chmod 600 /root/.ssh/authorized_keys && \
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      mkdir -p /run/sshd && \
      /usr/sbin/sshd -D"

  serverParis:
    image: ubuntu
    container_name: serverParis
    networks:
      custom-net:
        ipv4_address: 192.168.1.5
    ports:
      - "127.168.1.5:25:22"
    volumes:
      - C:\Users\juang\.ssh\id_rsa.pub:/root/.ssh/authorized_keys
    command: /bin/bash -c "\
      apt update && \
      apt install -y openssh-server && \
      mkdir -p /root/.ssh && \
      chown root:root /root/.ssh/authorized_keys && \
      chmod 600 /root/.ssh/authorized_keys && \
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      mkdir -p /run/sshd && \
      /usr/sbin/sshd -D"
      
networks:
  custom-net:
    external: true
